version: '3.8'

services:
#  database-redis:
#    container_name: redis
#    image: redis:alpine
#    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
#    ports:
#      - 127.0.0.1:6379:6379

  mysql:
    image: mysql:8.0
    container_name: batch_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: batchDB
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci